### ISSUE TITLE
tab completion on 'ml use' doesn't work

### ISSUE THREAD

**Issue by boegel** [hpcugent/Lmod-UGent#5] opened 2016-08-29 17:01 UTC
This is the result of `ml use /us<tab>`:

```
$ ml use /user-bash: _filedir: command not found
```

I guess we're missing the `bash-completion.noarch` RPM?

See also https://sourceforge.net/p/lmod/mailman/message/32849535/

**Comment by wpoely86** [comment] 2016-08-31 09:49
Yes, the issue is that it uses a helper function that's only defined when the `bash-completion.noarch` rpm is installed. So either remove that call or install the helper function.

**Comment by boegel** [comment] 2016-08-31 09:53
@wpoely86 or only use the function if it's available?

**Comment by boegel** [comment] 2016-08-31 16:43
see also https://github.com/TACC/Lmod/issues/86, may get fixed via https://github.com/TACC/Lmod/pull/157

**Comment by rtmclay** [comment] 2016-08-31 19:27
Yes. This is the same issue as #86 and is fixed with #157

**Comment by boegel** [comment] 2016-09-01 07:04
Lmod 6.5.5 indeed fixes the `_filedir` error being thrown, and makes tab completion for `ml use` work on paths. It doesn't work on environment variables though, would be nice if that worked too...
See also https://github.com/TACC/Lmod/issues/86#issuecomment-243993399

**Closed as completed** 2016-09-01 07:33 UTC
